name: Deploy Backend

on:
  push:
    branches:
      - main  # Ensure this matches your deployment branch

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Backend using Node.js 18

      - name: Sync Backend Directory
        run: |
          rsync -av --delete /home/ubuntu/actions-runner-backend/_work/Trilokpropco-Backend/Trilokpropco-Backend/ /home/ubuntu/Trilokpropco-Backend/

      - name: Install Dependencies
        run: |
          cd /home/ubuntu/Trilokpropco-Backend
          npm install

      - name: Start or Restart Backend with PM2
        run: |
          pm2 start /home/ubuntu/Trilokpropco-Backend/index.js --name Trilokpropco-Backend || pm2 restart Trilokpropco-Backend

      - name: Save PM2 process list
        run: |
          pm2 save

